### ISSUE TITLE
listOnEmpty should be passed explicitly to NestHydrationJS.nest() if needed at all

### ISSUE THREAD

**Issue by jurko-gospodnetic** [CoursePark/NestHydrationJS#1]
Currently the `NestHydrationJS.nest()` function's `listOnEmpty` value is deduced based on some _dirty_ `structPropToColumnMap` parameter type checking.

`structPropToColumnMap` value `true` or an array is used as an explicit `listOnEmpty` flag, which seems like a really unintuitive interface.

Besides being unintuitive, it is also wrong in at least one case - if you pass a `structPropToColumnMap` array and an empty data set, then you will always get an empty array as a response and there is no way to configure the function to do any differently. This is related to a `KnexNest` problem reported as https://github.com/CoursePark/KnexNest/issues/2.

Also the `listOnEmpty` value is set to `true` in case when `structPropToColumnMap` is an array, but is not directly used afterwards, and instead the `structPropToColumnMap` type gets rechecked later on instead.

My suggestion would be to simply make the function always return an empty array to indicate 'no data' and not make the no-data case special enough to warrant a completely different data type.

**Comment by dvalentiate** [comment]
Oops missed cleaning this up back when it was relevant. The issue was discussed and handled over at CoursePark/KnexNest#2.

> Besides being unintuitive, it is also wrong in at least one case - if you pass a structPropToColumnMap array and an empty data set, then you will always get an empty array as a response and there is no way to configure the function to do any differently. This is related to a KnexNest problem reported as CoursePark/KnexNest#2.

Not broken, if asking nest for an array, ya get one.

> Also the listOnEmpty value is set to true in case when structPropToColumnMap is an array, but is not directly used afterwards, and instead the structPropToColumnMap type gets rechecked later on instead.

True! Thanks, cleaned out unused code with fd4343d6d5d.

> My suggestion would be to simply make the function always return an empty array to indicate 'no data' and not make the no-data case special enough to warrant a completely different data type.

I disagree, I believe this would make the next function inconsistent with the type that is explicitly asked for either in the form of the data or by the hint value. Will not do.
