### ISSUE TITLE
specify which column is the "identifying column"

### ISSUE THREAD

**Issue by acarl005** [CoursePark/NestHydrationJS#10]
It looks like the first property in the definition object is assumed to be the column that uniquely identifies each object. It would be nice if there was a way to override this default behavior by specifying the name of the unique column in the object definition.

**Comment by dvalentiate** [comment]
By passing in a custom definition then the ids are specified manually and don't need to be the first properties. (I am uncertain on this, but this is intended behaviour and it is a bug if not working like this)

If using this library to automatically determine object structure from column names (typical usage) then yes it is assumed that the first property is an id for each level of object nesting.

It would be possible to add some kind of delimiter/marker to column names to mark them identity properties even if they were out of order in the definition object when automatically determine object structure but that would take some time and thinking to implement.

**Comment by acarl005** [comment]
Based on my understanding of the source code at https://github.com/CoursePark/NestHydrationJS/blob/master/NestHydrationJS.js#L220
```js
propList = _.keys(structPropToColumnMap);
		
if (propList.length === 0) {
	throw new Error('...');
}
		
idProp = propList[0];
idColumn = structPropToColumnMap[idProp].column || structPropToColumnMap[idProp];
```
it looks like the `idColumn` is always the first key in the object structure definition. I don't see any way to specify which column is the identifying column manually. I was hoping for something like this:

```js
var definition = [{
    title: 'title',
    required: {column: 'required', type: 'BOOLEAN'},
    id: {column: 'id', idColumn: true}, // force 'id' to be the idColumn, even though it is not first
    teacher: {
        id: {column: 'teacher_id', type: 'NUMBER'},
        name: 'teacher_name'
    }
}];
```
In this example, instead of `title`, which occurs first, being the identifying column, an option called `idColumn` could be placed in another column to make it the identifier.

My team and I really like this library. We are using it to convert flat SQL results to nested GraphQL objects. The object shape definition is being generated dynamically on each request. It was a little troublesome to ensure that every definition had the identifying column as the first property. This feature would make it easier. It would be much appreciated.

**Comment by dvalentiate** [comment]
@acarl005 thanks for the compliments. Seems reasonable enough. I'll take another look at this, hopefully over this weekend.

**Comment by dvalentiate** [comment]
@acarl005 0.4.0 brings in the ability to specify the id property in a definition or to get it from a column name with an `___ID` append to the column name. See the README for details.

**Comment by acarl005** [comment]
Awesome!! This will make my life a bit easier. Thanks for your work on NestHydrationJS.
