### ISSUE TITLE
Can't use it multiple times as scoped objects

### ISSUE THREAD

**Issue by hshafy** [CoursePark/NestHydrationJS#11]
I have a problem that if I want to use it several times in the code, data collide (for example when you have custom type that is already registered).

The problem is that you are exporting an object that bring a singleton that maintain state, If you export a function rather than an object and do a return inside it, it will bring a scoped object that can be used several times without any issue.

This change is easy, I can fork it and do it, but it will affect the usage instructions and will break others code! do you want me to do it?

**Comment by dvalentiate** [comment]
Yes the improvement sounds good. A pull request would be appreciated. I can increment the version number and that should make it safe for existing users.

**Comment by hshafy** [comment]
excellent, I will submit the PR soon.

**Comment by dvalentiate** [comment]
PR merged, problem solved, thanks for contributing @hshafy !

**Comment by hshafy** [comment]
Awesome, thank you for your prompt reply.
