### ISSUE TITLE
.NET Implementation of NestHydrationJS

### ISSUE THREAD

**Issue by sitereactor** [CoursePark/NestHydrationJS#37]
Hi there,

Thank you for creating this project - very handy in combination with Join Monster for GraphQL scenarios.

This is not really an issue, but didn't know how else to get in touch. 
We have created a .NET implementation of this library, as we needed something like this within the .NET ecosystem to handle the data coming back from postgresql before its handed off to a GraphQL Server (also .NET :)). I have added a link back to this project as you can see on the github project linked below, which I hope is cool. Let me know if you have input or feedback.

https://github.com/umbraco/nest-hydration-dotnet

**Comment by dvalentiate** [comment]
Wow thanks! I appreciate this! I've unfortunately been neglecting this project for a while now.

However I am learning Rust these days and think this project would be an excellent test bed for Rust and wasm. So my plans are to come back to updating NestHydrationJS, cleaning it up and also making a compatible Rust implementation. I'll be very interested in see what you have done with it and appreciate the compliment.

Again thank you.
